/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pizzawatch.gui.admin;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import pizzawatch.utils.UserUtils;

@SuppressWarnings("serial")
public class ManageCancellationReqsFrame extends javax.swing.JFrame
{
    public ManageCancellationReqsFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        spCancellationReqs = new javax.swing.JScrollPane();
        jtCancellationReqs = new javax.swing.JTable();
        lbTitle = new javax.swing.JLabel();
        btApprove = new javax.swing.JButton();
        btReject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtCancellationReqs.setModel(UserUtils.getCancelRequestedOrdersAllUsersTableModel());
        spCancellationReqs.setViewportView(jtCancellationReqs);

        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitle.setText("Manage Cancellation Requests");

        btApprove.setText("Approve");
        btApprove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btApproveActionPerformed(evt);
            }
        });

        btReject.setText("Reject");
        btReject.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(spCancellationReqs, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btApprove))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btReject, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spCancellationReqs, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btApprove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btReject)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btApproveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btApproveActionPerformed
    {//GEN-HEADEREND:event_btApproveActionPerformed
        //Loop through the column names and the one for the user ID
        //Have to do this every time as the columns can be rearranged
        TableModel tm = jtCancellationReqs.getModel();
        int tableModelOrderIDColumnNum = -1;
        for(int x = 0; x < tm.getColumnCount(); x++)
        {
            if(tm.getColumnName(x).equals(UserUtils.ORDER_ID_COLUMN_NAME))
            {
                tableModelOrderIDColumnNum = x;
                break;
            }
        }

        int selectedRow = jtCancellationReqs.getSelectedRow();
        if(selectedRow != -1 && tableModelOrderIDColumnNum != -1)
        {
            //tm.getValueAt(selectedRow, tableModelOrderIDColumnNum); //Order ID
            ((DefaultTableModel)tm).removeRow(selectedRow); //Remove the row from the table //TODO Casting fragility?
        }
    }//GEN-LAST:event_btApproveActionPerformed

    private void btRejectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btRejectActionPerformed
    {//GEN-HEADEREND:event_btRejectActionPerformed
        //Loop through the column names and the one for the user ID
        //Have to do this every time as the columns can be rearranged
        TableModel tm = jtCancellationReqs.getModel();
        int tableModelOrderIDColumnNum = -1;
        for(int x = 0; x < tm.getColumnCount(); x++)
        {
            if(tm.getColumnName(x).equals(UserUtils.ORDER_ID_COLUMN_NAME))
            {
                tableModelOrderIDColumnNum = x;
                break;
            }
        }

        int selectedRow = jtCancellationReqs.getSelectedRow();
        if(selectedRow != -1 && tableModelOrderIDColumnNum != -1)
        {
            //tm.getValueAt(selectedRow, tableModelOrderIDColumnNum); //Order ID
            ((DefaultTableModel)tm).removeRow(selectedRow); //Remove the row from the table //TODO Casting fragility?
        }
    }//GEN-LAST:event_btRejectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApprove;
    private javax.swing.JButton btReject;
    private javax.swing.JTable jtCancellationReqs;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JScrollPane spCancellationReqs;
    // End of variables declaration//GEN-END:variables
}
