/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pizzawatch.gui.admin;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

@SuppressWarnings("serial")
public class ManageCancellationReqsFrame extends javax.swing.JFrame
{
    public ManageCancellationReqsFrame()
    {
        initComponents();
    }

    private DefaultListModel getDefaultListModel()
    {
        DefaultListModel dlm = new DefaultListModel();
        dlm.addElement("Item 1");
        dlm.addElement("Item 2");
        dlm.addElement("Item 3");
        dlm.addElement("Item 4");

        return dlm;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        spCancellationReqs = new javax.swing.JScrollPane();
        jlCancellationReqs = new javax.swing.JList();
        lbTitle = new javax.swing.JLabel();
        btApprove = new javax.swing.JButton();
        btReject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlCancellationReqs.setModel(getDefaultListModel());
        jlCancellationReqs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        spCancellationReqs.setViewportView(jlCancellationReqs);

        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitle.setText("Manage Cancellation Requests");

        btApprove.setText("Approve");
        btApprove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btApproveActionPerformed(evt);
            }
        });

        btReject.setText("Reject");
        btReject.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(spCancellationReqs)
                    .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btApprove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btReject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spCancellationReqs, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btApprove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btReject)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btApproveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btApproveActionPerformed
    {//GEN-HEADEREND:event_btApproveActionPerformed
        Object selectValue = jlCancellationReqs.getSelectedValue();
        if(selectValue != null)
        {
            JOptionPane.showMessageDialog(this, "Approving: " + selectValue);
            //TODO: fix casting fragility
            DefaultListModel model = (DefaultListModel)jlCancellationReqs.getModel();
            model.removeElement(selectValue);
        }
    }//GEN-LAST:event_btApproveActionPerformed

    private void btRejectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btRejectActionPerformed
    {//GEN-HEADEREND:event_btRejectActionPerformed
        Object selectValue = jlCancellationReqs.getSelectedValue();
        if(selectValue != null)
        {
            JOptionPane.showMessageDialog(this, "Rejecting: " + selectValue);
            //TODO: fix casting fragility
            DefaultListModel model = (DefaultListModel)jlCancellationReqs.getModel();
            model.removeElement(selectValue);
        }
    }//GEN-LAST:event_btRejectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApprove;
    private javax.swing.JButton btReject;
    private javax.swing.JList jlCancellationReqs;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JScrollPane spCancellationReqs;
    // End of variables declaration//GEN-END:variables
}
