/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pizzawatch.gui.admin;

import javax.swing.JOptionPane;
import pizzawatch.utils.UserUtils;

@SuppressWarnings("serial")
public class MultipleUserPastOrdersFrame extends javax.swing.JFrame
{
    public MultipleUserPastOrdersFrame()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPastOrders = new javax.swing.JTable();
        lbUserIDs = new javax.swing.JLabel();
        tfUserIDs = new javax.swing.JTextField();
        btGetPastOrders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitle.setText("Past Orders (Multiple Users)");

        jtPastOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(jtPastOrders);

        lbUserIDs.setText("User IDs (use ; as delimeter):");

        btGetPastOrders.setText("Get Orders");
        btGetPastOrders.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btGetPastOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbUserIDs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfUserIDs))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitle)
                            .addComponent(btGetPastOrders))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserIDs)
                    .addComponent(tfUserIDs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btGetPastOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGetPastOrdersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btGetPastOrdersActionPerformed
    {//GEN-HEADEREND:event_btGetPastOrdersActionPerformed
        String[] userIDs = tfUserIDs.getText().split(";");
        if(userIDs.length > 0 && tfUserIDs.getText().isEmpty() == false)
        {
            jtPastOrders.setModel(UserUtils.getPastOrdersTableModel(userIDs));
        }
        else
        {
            JOptionPane.showMessageDialog(this, "You must enter at least one user ID!");
        }
    }//GEN-LAST:event_btGetPastOrdersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGetPastOrders;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPastOrders;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUserIDs;
    private javax.swing.JTextField tfUserIDs;
    // End of variables declaration//GEN-END:variables

}
