/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pizzawatch.gui;

import pizzawatch.sql.connection.JBDCSQLConnection;

@SuppressWarnings("serial")
public class MainFrame extends javax.swing.JFrame
{
    public MainFrame()
    {
        initComponents();

        JBDCSQLConnection sqlcon = new JBDCSQLConnection(); //TODO Make async
        sqlcon.setOracleConnection();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbTitle = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        UserPanel = new javax.swing.JPanel();
        btAddOrder = new javax.swing.JButton();
        btViewPendingOrders = new javax.swing.JButton();
        btViewPastOrders = new javax.swing.JButton();
        btRequestCancel = new javax.swing.JButton();
        cbUserID = new javax.swing.JComboBox();
        lbUserID = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        btManageCancellationReqs = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitle.setText("TMNT Pizza Watch");

        btAddOrder.setText("Add Order");
        btAddOrder.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btAddOrderActionPerformed(evt);
            }
        });

        btViewPendingOrders.setText("View Pending Orders");
        btViewPendingOrders.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btViewPendingOrdersActionPerformed(evt);
            }
        });

        btViewPastOrders.setText("View Past Orders");
        
        btViewPastOrders.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
            	btViewPastOrdersPerformed(evt);
            }
        });
        
        btRequestCancel.setText("Request Order Cancellation");
        btRequestCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btRequestCancelActionPerformed(evt);
            }
        });

        cbUserID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        cbUserID.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbUserIDActionPerformed(evt);
            }
        });

        lbUserID.setText("User ID");

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAddOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btViewPendingOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btViewPastOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRequestCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUserID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddOrder)
                    .addComponent(cbUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUserID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btViewPendingOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btViewPastOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRequestCancel)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("User", UserPanel);

        btManageCancellationReqs.setText("Manage Cancellation Requests");
        btManageCancellationReqs.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btManageCancellationReqsActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btManageCancellationReqs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btManageCancellationReqs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Admin", AdminPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btManageCancellationReqsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btManageCancellationReqsActionPerformed
    {//GEN-HEADEREND:event_btManageCancellationReqsActionPerformed
        ManageCancellationReqsFrame mcrf = new ManageCancellationReqsFrame();
        mcrf.setVisible(true);
    }//GEN-LAST:event_btManageCancellationReqsActionPerformed

    private void cbUserIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbUserIDActionPerformed
    {//GEN-HEADEREND:event_cbUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUserIDActionPerformed

    private void btAddOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAddOrderActionPerformed
    {//GEN-HEADEREND:event_btAddOrderActionPerformed
        AddOrderFrame aof = new AddOrderFrame();
        aof.setVisible(true);
    }//GEN-LAST:event_btAddOrderActionPerformed

    private void btViewPendingOrdersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btViewPendingOrdersActionPerformed
    {//GEN-HEADEREND:event_btViewPendingOrdersActionPerformed
        PendingOrdersFrame frame = new PendingOrdersFrame();
    	frame.setVisible(true);
    }//GEN-LAST:event_btViewPendingOrdersActionPerformed

    private void btRequestCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btRequestCancelActionPerformed
    {//GEN-HEADEREND:event_btRequestCancelActionPerformed
        //TODO
    }//GEN-LAST:event_btRequestCancelActionPerformed
    
    private void btViewPastOrdersPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btViewPendingOrdersActionPerformed
    {//GEN-HEADEREND:event_btViewPendingOrdersActionPerformed
        PastOrdersFrame frame = new PastOrdersFrame();
    	frame.setVisible(true);
    }//GEN-LAST:event_btViewPendingOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton btAddOrder;
    private javax.swing.JButton btManageCancellationReqs;
    private javax.swing.JButton btRequestCancel;
    private javax.swing.JButton btViewPastOrders;
    private javax.swing.JButton btViewPendingOrders;
    private javax.swing.JComboBox cbUserID;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUserID;
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
