/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pizzawatch.gui;

import pizzawatch.datamodels.User;
import pizzawatch.gui.admin.ManageCancellationReqsFrame;
import pizzawatch.gui.admin.MultipleUserPastOrdersFrame;
import pizzawatch.gui.user.AddOrderFrame;
import pizzawatch.gui.user.PastOrdersFrame;
import pizzawatch.gui.user.PendingOrdersFrame;
import pizzawatch.gui.user.RequestCancellationFrame;

@SuppressWarnings("serial")
public class MainFrame extends javax.swing.JFrame
{
    private final LoginFrame lf;
    private final User currentUser;

    public MainFrame(LoginFrame lf, User user)
    {
        this.lf = lf;
        this.currentUser = user;

        initComponents();

        if(currentUser.isAdmin() == false)
        {
            mainTabbedPane.setEnabledAt(1, false);
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbTitle = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        UserPanel = new javax.swing.JPanel();
        btAddOrder = new javax.swing.JButton();
        btViewPendingOrders = new javax.swing.JButton();
        btViewPastOrders = new javax.swing.JButton();
        btRequestCancel = new javax.swing.JButton();
        btEditUserDetails = new javax.swing.JButton();
        AdminPanel = new javax.swing.JPanel();
        btManageCancellationReqs = new javax.swing.JButton();
        btMultiplerUserPastOrders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                unhideLoginFrame(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitle.setText("TMNT Pizza Watch");

        btAddOrder.setText("Add Order");
        btAddOrder.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btAddOrderActionPerformed(evt);
            }
        });

        btViewPendingOrders.setText("View Pending Orders");
        btViewPendingOrders.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btViewPendingOrdersActionPerformed(evt);
            }
        });

        btViewPastOrders.setText("View Past Orders");
        btViewPastOrders.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btViewPastOrdersActionPerformed(evt);
            }
        });

        btRequestCancel.setText("Request Order Cancellation");
        btRequestCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btRequestCancelActionPerformed(evt);
            }
        });

        btEditUserDetails.setText("Edit User Details");
        btEditUserDetails.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btEditUserDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAddOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btViewPendingOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btViewPastOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRequestCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btEditUserDetails)
                .addContainerGap())
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddOrder)
                    .addComponent(btEditUserDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btViewPendingOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btViewPastOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRequestCancel)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("User", UserPanel);

        btManageCancellationReqs.setText("Manage Cancellation Requests");
        btManageCancellationReqs.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btManageCancellationReqsActionPerformed(evt);
            }
        });

        btMultiplerUserPastOrders.setText("View Past Orders (multiple users)");
        btMultiplerUserPastOrders.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btMultiplerUserPastOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btManageCancellationReqs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMultiplerUserPastOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btManageCancellationReqs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMultiplerUserPastOrders)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Admin", AdminPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btManageCancellationReqsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btManageCancellationReqsActionPerformed
    {//GEN-HEADEREND:event_btManageCancellationReqsActionPerformed
        ManageCancellationReqsFrame mcrf = new ManageCancellationReqsFrame();
        mcrf.setVisible(true);
    }//GEN-LAST:event_btManageCancellationReqsActionPerformed

    private void btAddOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAddOrderActionPerformed
    {//GEN-HEADEREND:event_btAddOrderActionPerformed
        AddOrderFrame aof = new AddOrderFrame();
        aof.setVisible(true);
    }//GEN-LAST:event_btAddOrderActionPerformed

    private void btRequestCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btRequestCancelActionPerformed
    {//GEN-HEADEREND:event_btRequestCancelActionPerformed
        RequestCancellationFrame rcf = new RequestCancellationFrame();
        rcf.setVisible(true);
    }//GEN-LAST:event_btRequestCancelActionPerformed

    private void unhideLoginFrame(java.awt.event.WindowEvent evt)//GEN-FIRST:event_unhideLoginFrame
    {//GEN-HEADEREND:event_unhideLoginFrame
        lf.setVisible(true);
    }//GEN-LAST:event_unhideLoginFrame

    private void btEditUserDetailsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btEditUserDetailsActionPerformed
    {//GEN-HEADEREND:event_btEditUserDetailsActionPerformed
        AddOrEditUserFrame frame = new AddOrEditUserFrame(currentUser);
        frame.setVisible(true);
    }//GEN-LAST:event_btEditUserDetailsActionPerformed

    private void btViewPastOrdersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btViewPastOrdersActionPerformed
    {//GEN-HEADEREND:event_btViewPastOrdersActionPerformed
        PastOrdersFrame frame = new PastOrdersFrame(new String[] {currentUser.getUserID()});
    	frame.setVisible(true);
    }//GEN-LAST:event_btViewPastOrdersActionPerformed

    private void btViewPendingOrdersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btViewPendingOrdersActionPerformed
    {//GEN-HEADEREND:event_btViewPendingOrdersActionPerformed
        PendingOrdersFrame frame = new PendingOrdersFrame();
    	frame.setVisible(true);
    }//GEN-LAST:event_btViewPendingOrdersActionPerformed

    private void btMultiplerUserPastOrdersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btMultiplerUserPastOrdersActionPerformed
    {//GEN-HEADEREND:event_btMultiplerUserPastOrdersActionPerformed
        MultipleUserPastOrdersFrame frame = new MultipleUserPastOrdersFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_btMultiplerUserPastOrdersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton btAddOrder;
    private javax.swing.JButton btEditUserDetails;
    private javax.swing.JButton btManageCancellationReqs;
    private javax.swing.JButton btMultiplerUserPastOrders;
    private javax.swing.JButton btRequestCancel;
    private javax.swing.JButton btViewPastOrders;
    private javax.swing.JButton btViewPendingOrders;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
