/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pizzawatch.gui.user;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Random;

import pizzawatch.datamodels.Order;
import pizzawatch.datamodels.User;
import pizzawatch.sql.sqlreader.ResultSetParser;
import pizzawatch.sql.sqlreader.SqlScriptReader;
import pizzawatch.utils.OrderUtils;

@SuppressWarnings("serial")
public class AddOrderFrame extends javax.swing.JFrame
{
    private final String[] prices;
    private SqlScriptReader SQL_READER = SqlScriptReader.getInstance();
    private User currentUser;

    @SuppressWarnings("unchecked")
    public AddOrderFrame(User currentUser)
    {
    	this.currentUser = currentUser;
        initComponents();
        
        tfPrice.setEnabled(false);

        ArrayList<LinkedList<String>> pizzaTypeInfo = OrderUtils.getPizzaTypeInfo();
        prices = OrderUtils.getAttributesFromPizzaTypeInfo(pizzaTypeInfo, 1, "999.99");
        cbPizzaType.setModel(OrderUtils.getPizzaTypesComboBoxModel(OrderUtils.getAttributesFromPizzaTypeInfo(pizzaTypeInfo, 0, "Pepperoni")));
        cbPizzaType.setSelectedIndex(0); //Fire off an event to init tfPrice
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbAddOrder = new javax.swing.JLabel();
        lbPizzaType = new javax.swing.JLabel();
        lbDeliveryMethod = new javax.swing.JLabel();
        cbPizzaType = new javax.swing.JComboBox();
        cbDeliveryMethod = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        lbPrice = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbAddOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAddOrder.setText("Add Order");

        lbPizzaType.setText("Pizza Type:");

        lbDeliveryMethod.setText("Delivery Method:");

        cbPizzaType.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbPizzaTypeActionPerformed(evt);
            }
        });

        cbDeliveryMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Car", "Boat", "Delivery Person" }));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                submitButtonActionPerformed(evt);
            }
        });

        lbPrice.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAddOrder)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDeliveryMethod)
                            .addComponent(lbPizzaType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbPizzaType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDeliveryMethod, 0, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbAddOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPizzaType)
                    .addComponent(cbPizzaType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrice)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDeliveryMethod)
                    .addComponent(cbDeliveryMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPizzaTypeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbPizzaTypeActionPerformed
    {//GEN-HEADEREND:event_cbPizzaTypeActionPerformed
        //Set the price text field accordingly whenever the selected pizza type changes
        tfPrice.setText(prices[cbPizzaType.getSelectedIndex()]);
    }//GEN-LAST:event_cbPizzaTypeActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_submitButtonActionPerformed
    {//GEN-HEADEREND:event_submitButtonActionPerformed
    	ArrayList<LinkedList<String>> user_location = ResultSetParser.parseResultSetIntoArray(SQL_READER.query("SELECT address FROM User_IsIn WHERE userID = " + "'" + currentUser.getUserID()+ "'"), "address");
    	Random rng = new Random();
    	Order newOrder = new Order(rng.nextInt(10000000), currentUser.getUserID(), user_location.get(0).get(0) ,cbPizzaType.getSelectedItem().toString(), cbDeliveryMethod.getSelectedItem().toString(),0,0);
    	OrderUtils.addOrder(newOrder);
    	this.setVisible(false);
    	this.dispose();
    	
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbDeliveryMethod;
    private javax.swing.JComboBox cbPizzaType;
    private javax.swing.JLabel lbAddOrder;
    private javax.swing.JLabel lbDeliveryMethod;
    private javax.swing.JLabel lbPizzaType;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables
}
